name = "JuliaPackageTemplate"
uuid = "96dde3b6-0330-4a43-9eaa-52c937a74b0e"
authors = ["Javier González Monge"]
version = "1.0.0-DEV"

[deps]
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"

[compat]
Aqua = "0.8"
DispatchDoctor = "0.4.19"
Test = "1.11"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Aqua", "Test", "TestItemRunner", "TestItems"]
